# Generated by Django 5.2.5 on 2025-09-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
    ]
