# Generated by Django 5.2.5 on 2025-10-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_backfill_notes_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.notesgroup'),
        ),
    ]
